"""用户头像

Revision ID: 10510b119110
Revises: 6f8521de0421
Create Date: 2020-07-31 21:49:18.529487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10510b119110'
down_revision = '6f8521de0421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
